### ISSUE TITLE
Problemas no Sistema

### ISSUE THREAD

**Issue by dmctec** [loiane/masteringextjs#21]
Olá Loiane, 

Gostaria muito da sua ajuda, para rodar este sistema 100%, tenho o livro Mastering Ext JS - Second Edition em pdf e estou estudando ele, mais comecei a ter dificuldades de fazer o sistema do zero pelo livro e então procurei baixar o codigo do sistema pronto e estudar ele junto com o livro, mais o sistema não esta funcionando 100%, estou com muita dificuldade de colocar ele funcional para poder continuar estudando. Estou tendo problemas com os dados do banco que parece estar faltando dados para o sistema funcionar, consegui com dificuldades chegar a mostrar o menu, mais ele não aparece as descrições e o painel esta com problemas e o icone esta cortando, pode me ajudar, só gostaria dele funcional 1005 para continuar estudando com o livro. 

Adoro seu trabalho e seus Videos, sou seu Fan :)
Não sou bom no inglês, sei somente o básico, uso muito o google tradutor para estudar ^^
Muito obrigado, 
David

**Comment by loiane** [comment]
Oi David, obrigada!
Veja o vídeo de instalação: http://youtu.be/Vm6meIDTHdw
Precisa ter tudo instalado direitinho. Tem um link no cap 2 ou 3 logo no início com passo a passo.

**Comment by dmctec** [comment]
Loiane, 
Eu fiz o passo a passo do video e procurei sobre o link no livro que vc falou e achei o do livro http://www.packtpub.com, eu entrei com meu login e baixei o codigo que esta diponivel lá, mais continuou com o mesmo erro. Se puder me ajudar mais um pouco eu agradeço. Obrigado pela Atenção.
- segue abaixo as imagens do menu sem carregar e os dados do banco de dados sakila:
  ![erro-menu](https://cloud.githubusercontent.com/assets/11961533/7164198/1530373a-e375-11e4-8da1-9a5b38d2d0e5.jpg)
  ![erro-sakila](https://cloud.githubusercontent.com/assets/11961533/7164203/1906faba-e375-11e4-96d4-99c6b8423ead.jpg)

**Comment by loiane** [comment]
o menu está renderizando e está mostrando os ícones, isso significa que está obtendo os dados do banco.
Veja os arquivos de traduçao se estao no local correto. Abra o google developer tools e debugue pra ver pq nao está sendo carregado. A nível de código não está tendo nenhum problema - somente debugando mesmo pra ver o que está acontecendo.

**Comment by dmctec** [comment]
Era o arquivo pt_BR.js que estava faltando dados de tradução por isso não mostrava nada, obrigado. 
Agora surgiu outro problema quando vou tentar adicionar um novo usuário aparece erro segue abaixo:
![erro-add](https://cloud.githubusercontent.com/assets/11961533/7166052/e94a6502-e381-11e4-921c-b9905175c86b.jpg)
- esta aparecendo também uma barra horizontal de rolagem fixa em cada categoria do menu, você pode ver o que estou falando na primeira imagem que enviei.
- outra coisa que eu percebi também o ícone de abrir e fechar as categorias do menu esta em formato diferente do exemplo que vc fez do vídeo, esta cortando.

(não tem nenhum código fonte do projeto sem nenhum problema para baixar? todos que eu encontrei estão ruins. Gostaria muito para eu poder estudar melhor, obrigado.)
