### ISSUE TITLE
MainTabPanel.js

### ISSUE THREAD

**Issue by yalmar** [loiane/masteringextjs#22]
this file is missing on the classic/src/view/main folder

**Comment by loiane** [comment]
Hi, please take a look at branch 5.x, it contains source code of the book,
Branch 6.x is working in progress as mentioned in readme file.

**Comment by toeasy** [comment]
there is no file named MainTabPanel.js , so run from sencha cmd build cannot success.
how can i run it successful in sencha cmd 6.x or 5.x

**Comment by loiane** [comment]
Hi, please take a look at branch 5.x, it contains source code of the book,
Branch 6.x is working in progress as mentioned in readme file.
